pipeline {

	agent any
	

  stages {
	 stage('cd to website') {

      steps {

      	sh 'cd website'

      } 
  } 
         stage('Docker Build') {

      steps {

      	sh 'docker build -t website website/'

      } 
  }
        stage('Deploy Container') {

      steps {

      	sh 'docker run -d -P website '

      } 
  }
} 
}
