pipeline {

	agent any
	

  stages {
	 stage('cd to website') {

      steps {

      	sh 'cd website'

      } 
  } 
         stage('Docker Build') {

      steps {

      	sh 'sudo docker build -t website website/'

      } 
  }

} 
}
